# general information
model_name: "Gazebo Standard Plane"
model_type: "Standard Plane Longitudinal Model"
model_class: "FixedWingRollModel_NonLinear"
# extractor_class: "FixedWingExtractorModel"

# extractor_config:
#   vmin: 8.0
#   vmax: 20.0
extractor_class: "Not implemented"

extractor_config:
  "Not implemented"

  # all vectors in FRD body frame if not specified otherwise
model_config:
  mass: 1
  moment_of_inertia:
    Ixx: 1
    Iyy: 1
    Izz: 1

  aerodynamics:
    type: "NonLinearWingRollModel"
    area: 0.41
    chord: 0.19
    stall_angle_deg: 20
    sig_scale_factor: 30

dynamics_model_config:
  optimizer_config:
    optimizer_class: "NonLinearRegressor"
    optimzation_parameters:
    parameter_bounds:
      c_L_al: !!python/tuple [0.0, .inf]
      c_L_ar: !!python/tuple [-.inf, 0.0]
      c_L_pv: !!python/tuple [-.inf, .inf]
      t_d: !!python/tuple [0, .inf]
    initial_guess:
      c_L_al: 0.1
      c_L_ar: -0.1
      c_L_pv: -1
      t_d: 0.01
   
  estimate_forces: False
  estimate_moments: True
  resample_freq: 50.0
  estimate_angular_acceleration: False
  data:
    required_ulog_topics:
      vehicle_local_position:
        ulog_name:
          - "timestamp"
          - "vx"
          - "vy"
          - "vz"
      vehicle_attitude:
        ulog_name:
          - "timestamp"
          - "q[0]"
          - "q[1]"
          - "q[2]"
          - "q[3]"
        dataframe_name:
          - "timestamp"
          - "q0"
          - "q1"
          - "q2"
          - "q3"
      vehicle_angular_velocity:
        ulog_name:
          - "timestamp"
          - "xyz[0]"
          - "xyz[1]"
          - "xyz[2]"
          - "xyz_derivative[0]"
          - "xyz_derivative[1]"
          - "xyz_derivative[2]"
        dataframe_name:
          - "timestamp"
          - "ang_vel_x"
          - "ang_vel_y"
          - "ang_vel_z"
          - "ang_acc_b_x"
          - "ang_acc_b_y"
          - "ang_acc_b_z"
      sensor_combined:
        ulog_name:
          - "timestamp"
          - "accelerometer_m_s2[0]"
          - "accelerometer_m_s2[1]"
          - "accelerometer_m_s2[2]"
        dataframe_name:
          - "timestamp"
          - "acc_b_x"
          - "acc_b_y"
          - "acc_b_z"
      vehicle_thrust_setpoint:
        ulog_name:
          - "timestamp"
          - "xyz[0]"
        dataframe_name:
          - "timestamp"
          - "throttle"
      vehicle_torque_setpoint:
        ulog_name:
          - "timestamp"
          - "xyz[0]"
          - "xyz[1]"
          - "xyz[2]"
        dataframe_name:
          - "timestamp"
          - "aileron" # differential input to ailerons
          - "elevator" # elevator input
          - "rudder" # rudder input
      vehicle_land_detected:
        ulog_name:
          - "timestamp"
          - "landed"
        dataframe_name:
          - "timestamp"
          - "landed"
      vehicle_air_data:
        ulog_name:
          - "timestamp"
          - "rho"
      airspeed:
        ulog_name:
          - "timestamp"
          - "true_airspeed_m_s"   
      actuator_servos:
        ulog_name:
          - "timestamp"
          - "control[0]"
          - "control[1]"
          - "control[2]"
        dataframe_name:
          - "timestamp"
          - "c0"
          - "c1"
          - "c2"

